---
# tasks file for qnsmarti_stage2
- name: Add content to /opt/lampp/phpmyadmin/config.inc.php
  template:
    src: xampp-config-inc-php.j2
    dest: /opt/lampp/phpmyadmin/config.inc.php
- name: Create /opt/tomee/conf/Catalina/localhost/ROOT.xml
  file:
    path: /opt/tomee/conf/Catalina/localhost/ROOT.xml
    state: touch
- name: add content  to ROOT.xml
  template:
    src: root-xml.j2
    dest: /opt/tomee/conf/Catalina/localhost/ROOT.xml
- name: stat of war file in webapps
  stat: 
    path: /opt/tomee/webapps/ultima-2.0.17-12-2022-1
  register: war_status

- name: Move war to /opt/tomee
  command: mv /opt/tomee/webapps/ultima-2.0.17-12-2022-1 /opt/tomee/QnLive
  when: war_status.stat.exists
- name: Remove war file
  file:
    path: /opt/tomee/webapps/ultima-2.0.17-12-2022-1.war
    state: absent
- name: Sleep for 5 seconds
  pause:
    seconds: 5
- name: Restart tomee service
  systemd:
    name: tomee.service
    state: restarted

